### ISSUE TITLE
Spotting species incorrect name endings 

### ISSUE THREAD

**Issue by debpaul** [sfg-taxonpages/phasmida#2]
Paul Brock pauldbrock@btinternet.com @pbrockPhas 
Email noting he's finding some issues with name endings being incorrect.

- [ ] Paul, are these incorrect in old SF?
- [ ] @proceps does **soft validation** in TW find these?
  - [ ] is there a way in TW to group all the **soft validation** assertions?
  - [ ] in other words, can Paul find all the names that **soft validation** finds incorrect? Or can he only find them one-at-a-time (when perusing TaxonPages)?

**Comment by proceps** [comment]
please use https://docs.taxonworks.org/guide/Manual/nomenclature.html#new-synonymy-or-removal-from-synonymy-stat-rev as a reference guide how to update TaxonNames.
Soft validation could be used as a guide, but it will not resolve 100% of the cases.
At the moment we do not index soft-validations on the project level. There is an open issue on the github (https://github.com/SpeciesFileGroup/taxonworks/issues/2546). There is some limited functionality in Filter nomenclature, for example to search all names with/without specific taxon-name-classification.

**Comment by pbrockPhas** [comment]
Dmitry - thanks, passed a list of several names onto the SF team (yes, correct on SF but not on TW).

**Comment by debpaul** [comment]
@pbrockPhas next steps for fixing incorrect name endings:

1. you need to fix them, inside TaxonWorks (not your public TaxonPages and not in PSF old site).
 - so go here https://sfg.taxonworks.org and login to the `Phasmida Species File`
2. See steps below for how to get to `Edit Taxon Name` and check to see if the `gender and form` is set and if not, to set it.
3.  At least in this first example, the issue is not that the ending is "incorrect" on the `specific epithet`. Rather, it's that the gender for the genus is not set in the database. Once the genus had a specified gender, the ending on the specific epithet will be fixed by the software.
4. Once you make these fixes, they will appear a short time later on the public TaxonPages website correctly.

Example:
- _Baculofractum insignis_ needs to have `specific epithet` ending `insigne`.
- Inside TaxonWorks > Browse Nomenclature task > search `Baculofractum`
- First item that appears seems correct match > click on it to see the database record for this genus.
- Click on the `edit` pencil which opens `Edit Taxon Name`
- Scroll down to the `gender or form` section.
- Note that it's not specified.
- Select the correct `gender or form`
- Click save.
- Result: the specific epithet ending will change now, automatically.

![image](https://github.com/sfg-taxonpages/phasmida/assets/2990155/7a1651d1-f2b0-4d81-be71-144435f48075)

![image](https://github.com/sfg-taxonpages/phasmida/assets/2990155/49211dd8-836e-4d0d-896a-f654561157e8)


Note: I did not check the other names. @mjy suggests it's likely the same issue for the other names in your list:

List:
Baculofractum insignis in TW should read: insigne
Anchiale spinicolle in TW should read: spinicollis
Malacomorpha spinicolle in TW should read: spinicollis
Ceroys (Ceroys) coronatum in TW should read: coronatus
Tisamenus draconinus in TW should read: draconina
Calvisia (Nigracalvisia) grosse-granosa in TW should read: grossegranosa
Necroscia involute-cercata in TW should read: involutecercata
Sipyloidea gulare in TW should read: gularis
Rhamphophasma spinicornis in TW should read: spinicorne
Ctenomorpha marginipenne in TW should read: marginipennis

We can help you walk through these on any Wednesday too, together. Or we can set up a time to meet with you to walk you through it if our Wednesday times don't fit at the moment.

**Comment by proceps** [comment]
@pbrockPhas, there is a difference how names are stored in the original SF and in TW. In SF, the species epithet is stored in its currenct form, that meens that the name have to be updated manually, each time you change the genus. In TW, the epithet is saved as a protonym, in the original form. This means that the information is need to be entered only once, and when the species is moved from a genus to another one, the ending should be automatically updated, if the information about the gender and part of speach is in the DB. We did a lot of assumtions, when we converted nomenclator from the original SF to TW. And the nomenclator in the original SF was not used consistently among the projects. So yes, as @debpaul said, we may loose some data during conversion. We try to be little bit more moderate on assumtions, so that we may loose some information, but not to introduce artificial data in the database, which would be even harder to find in a long run. Unfortunattely conversion never come smooth, something is always lost. We estimate success if we can transfer 95-98% of the data correctly, and expect the users cover the remaining 2-5%. We think that in longer run, the data preserved in TW has much more internal integrity than original SF database, that is why we started the development in a first place. We also put a lot of efforts to do nomenclatural validation in the TW, so in many cases, we can predict and suggest the ajectival part of speach for the name, although we do not do the automatic assertions, letting the author to preview the suggestion first.

**Comment by pbrockPhas** [comment]
Thanks for the advice/background. The first worked out well, as I know the gender for the genus. However, others may be more complex, as it is not always easy to work out what the gender is - I do not want to assume, and if I press the button that could change other species names. I will have a think about these. I had a go at the names with a hypen in. It looks like changing the gender on the genus would have no impact on that, but the options I selected whilst trying to edit the species Calvisia (Nigracalvisia) grossegranosa did not work, as it still shows as grosse-granosa. I may have to join one of your meetings to sort examples like these out!

**Comment by debpaul** [comment]
Update: we reviewed and covered some of how to edit these names at 21 Sept 2023 SF Curators meeting.

**Comment by pbrockPhas** [comment]
All now fixed, thanks. It is not always clear whether gender is masculine or feminine - but Judith Marshall (ex. NHM) helped and we managed to work out which species names are nouns.
